import os
import numpy as np
import xarray as xr
from . lluv import read_lluv


def read_ruv(filename):
    """
    Reads Radial Velocities files (.ruv) generated by CODAR SeaSonde High-Frequency radar

    Paramaters
    ----------
    filename : string
        File name of the file to be read

    Returns
    -------
    data : xarray Dataset
        Data and metadata contaned in the file without additional tables
    """

    # Variables information

    varinfo = {"lond": {"long_name": "Longitude", "units": "degrees East"},
               "latd": {"long_name": "Latitude", "units": "degrees North"},
               "velu": {"long_name": "Zonal Velocity", "units": "cm/s"},
               "velv": {"long_name": "Merdional Velocity", "units": "cm/s"},
               "vflg": {"long_name": "Vector Flag", "units": "GridCode"},
               "espc": {"long_name": "Spatial Quality", "units": "n/a"},
               "etmp": {"long_name": "Temporal Quality", "units": "n/a"},
               "edtp": {"long_name": "Pattern distance", "units": "n/a"},
               "easn": {"long_name": "Signal to Noise Ratio", "units": "dB"},
               "maxv": {"long_name": "Velocity Maximum", "units": "cm/s"},
               "minv": {"long_name": "Velocity Minimum", "units": "cm/s"},
               "ersc": {"long_name": "Spatial Count", "units": "n/a"},
               "ertc": {"long_name": "Temporal Count", "units": "n/a"},
               "xdst": {"long_name": "X Distance", "units": "km"},
               "ydst": {"long_name": "Y Distance", "units": "km"},
               "rnge": {"long_name": "Range", "units": "km"},
               "bear": {"long_name": "Bearing", "units": "Degrees from North clokwise"},
               "velo": {"long_name": "Velocity", "units": "cm/s"},
               "head": {"long_name": "Direction of velocity", "units": "degrees North"},
               "sprc": {"long_name": "Spectra Range Cell", "units": "n/a"}}

    # Read the LLUV file

    data = read_lluv(filename)

    # Mesurements parameters

    time = data['metadata']['TimeStamp']  # Time
    drange = float(data['metadata']['RangeResolutionKMeters'])
    ncells = int(data['metadata']['RangeEnd'])  # Number of range cells
    angres = data['metadata']['AngularResolution']  # Angular resolution

    # Reajust some parameters, if needed.

    angres = int(angres.split(' ')[0])  # Assume that angres = "5 deg"

    # Time

    time = '-'.join(time.split(' ')[:3]) + 'T' + ':'.join(time.split(' ')[3:])
    time = np.array([time], dtype='datetime64[s]')

    # Range

    rang = (np.arange(ncells) + 1) * drange

    # Range cell index

    j = data['data']['sprc'].astype(int) - 1

    # Bearings

    nbear = 360 // angres
    bear0 = np.mod(data['data']['bear'], angres)[0]  # Initial bearing
    bear = bear0 + np.arange(nbear) * angres

    # bearing index

    i = ((data['data']['bear'] - bear0) // angres).astype(int)

    # Reshape data

    out = {}
    for varname in data['data'].keys():
        if varname != 'secondary_tables':

            # Create a maksed array with the data

            field = np.ma.array(data=np.zeros((ncells, nbear)),
                                mask=np.ones((ncells, nbear), dtype=bool))
            if varname in ['vlfg']:
                field.data[j, i] = data['data'][varname].astype(np.uint16)
            elif varname in ['ersc', 'ertc', 'sprc']:
                field.data[j, i] = data['data'][varname].astype(int)
            else:
                field.data[j, i] = data['data'][varname]
            field.mask[j, i] = False

            if varname in varinfo.keys():
                attrs = {"long_name": varinfo[varname]['long_name'],
                         "units": varinfo[varname]['units']}
            else:
                attrs = {"long_name": 'n/a',
                         "units": 'n/a'}

            # Create the xarray data array

            out.update({varname: xr.DataArray(field[np.newaxis, :, :],
                                              attrs=attrs,
                                              dims=("time", "range", "bearing"))})

    # Build the output dataset

    out = xr.Dataset(out,
                     attrs=data['metadata'],
                     coords={"time": time, "range": rang, "bearing": bear})
    out.coords['range'].attrs['long_name'] = 'Range'
    out.coords['range'].attrs['units'] = 'km'
    out.coords['bearing'].attrs['long_name'] = 'Bearing'
    out.coords['bearing'].attrs['units'] = 'degrees'
    out.attrs['filename'] = os.path.basename(filename)

    return out
